### ISSUE TITLE
Template for MinimumLength condition and SerchingEvent

### ISSUE THREAD

**Issue by adopilot** [Blazored/Typeahead#111]
First at all thank you on such great control.
In js world I am fun of select2, I think that select2 was needed 4 years to get degree of development where is Typeahed now.

It will be great if we could return user message that need to type more chars before control trigger searching.
![image](https://user-images.githubusercontent.com/4448913/73728753-2c942800-4734-11ea-9a04-b70af004d7d0.png)
___

Also searching template will be great, so we can tell user that we are searching ,Spiner is there but it occurs in left side of control and many users do not notice it.

**Comment by vertonghenb** [comment]
Agreed, this would be a huge UX improvement.

Quick todo:
- [ ] Add Parameter, any suggestions for the name?
- [ ] on each debounce trigger to show the text.
- [ ] Do we show the text initially?

Feedback would be nice!

**Comment by calebhughes** [comment]
Parameter name could be something like: HelpTemplate or HelperTemplate.

I think the text should only show after the first debounce of input if they don't hit the required length personally. This way users don't see a text they may never need because they are going to enter a valid search the first try.
