### ISSUE TITLE
[Bug] Preselected Items won't remove on click

### ISSUE THREAD

**Issue by mkchx** [Blazored/Typeahead#135]
**Describe the bug**
For the multi-selection option, suppose we have pre-selected items.
Once you click any element that was added from the UI drop-down the item is being added twice instead of removing it from the UI.

**Expected behavior**
Should remove the clicked item from the UI component

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
![Screenshot 2020-05-08 at 2 35 43 PM](https://user-images.githubusercontent.com/13793844/81402060-59901680-9139-11ea-99cc-e70f7c0b5853.png)

**Comment by chrissainty** [comment]
Thanks for raising this @mkchx. We use [`List<T>.Contains(T)`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.contains?view=netcore-3.1) to check for an existing item in the list. This means for complex objects you need to implement `IEquatable<T>` on the objects you're passing us otherwise there is no way for us to know that two objects are the same.
