### ISSUE TITLE
[Bug] Prevents focus of input elements in nested modals

### ISSUE THREAD

**Issue by robertsundstrom** [Blazored/Typeahead#187]
I have two modals (Blazored). One is nested and opened from the first one. Both have Typeahead controls with other form elements in them. When the second modal opens I'm just able to click Typeahead controls and all the other elements except the input controls. I can not select an input field in the nested modal to input text. 

The control in the original modal also seems to be focused.

**Comment by chrissainty** [comment]
Hi Robert, could you provide a screen capture or a repro of the issue? It's a little hard to understand what is going on from your explaination.

**Comment by robertsundstrom** [comment]
I cannot focus any field in the top modal, except the Select.

<img width="503" alt="Screen Shot 2020-12-19 at 17 02 11" src="https://user-images.githubusercontent.com/919580/102693588-024c3b80-421c-11eb-8b9a-c023502a2358.png">

**Comment by chrissainty** [comment]
@robertsundstrom Apologies for not clocking this earlier but this would probably be better filed in the Modal repo as this doesn't appear to have anything to do with the Typeahead control. I'm going to close the issue here to keep things tidy, if you're still having a problem then please raise an issue on that repo.

**Comment by robertsundstrom** [comment]
@chrissainty This is what I discovered the problem to be: https://github.com/Blazored/Modal/issues/291#issuecomment-781521894
