### ISSUE TITLE
TwoWay Binding of Value

### ISSUE THREAD

**Issue by ScholliYT** [Blazored/Typeahead#35]
I want to set the currently selected `Value` from the outside. Looks like we need to add some kind of UI state refresh if `Value` changes.

I might make up a PR for this.

**Comment by vertonghenb** [comment]
This should already be supported since we "refresh the UI" OnParametersSet
https://github.com/Blazored/Typeahead/blob/b3f38b891cd536c9c4590a9d57d86ad1673f5f49/src/Blazored.Typeahead/Forms/BlazoredTypeaheadInput.razor.cs#L96

I'm not sure which version you're currently using. 
@chrissainty did we already release the latest PR?

**Comment by chrissainty** [comment]
I'm open to your opinion on this,@vertonghenb. But I would prefer we hold off releasing the current set of changes until Preview 9 lands, Dan Roth said that should be Tuesday or Wednesday next week. 

This would avoid having to do two releases in quick succession and if we wait for Preview 9 we should hopefully get the fixes for Razor Class Libraries as well. There are more breaking APIs in Preview 9 as well. Which is going to be fun!

**Comment by vertonghenb** [comment]
@chrissainty agreed!

**Comment by vertonghenb** [comment]
@ScholliYT Closing this since the package was recently updated to preview-9 and this change was fixed by #31
