### ISSUE TITLE
Unable to enter text without mouse click

### ISSUE THREAD

**Issue by rgamage** [Blazored/Typeahead#91]
With my testing so far (v 4.2.0), I am unable to use the typeahead control as a keyboard-centric user.  I tab through the form's controls until the typeahead has focus, then try to start typing.  Nothing happens.  No apparent way to start entering text until I click with the mouse inside the input box.

It would be great if, upon gaining focus, the typeahead control was able to receive keyboard input.

**Comment by chrissainty** [comment]
Could you clarify how you've tested this? I've just spun up the sample app and can tab into a typeahead fine and start typing without issue. 

Are you trying this with an empty typeahead or one with an already selected value?

**Comment by vincentw56** [comment]
I can confirm this. If I tab from a field to the Type Ahead field, I cannot type anything. I have to click in it with the mouse before I can start typing. This is with a new field with no text inside of it. I am using Core 3.1 and 4.2.0.

**Comment by chrissainty** [comment]
Could you create a repro showing this behaviour as I can't seem replicate
it.

**Comment by vincentw56** [comment]
Here is a little more info. When I tab into the TypeAhead, it works if I press enter first. Once I do that, I can start typing. It looks like the control doesn't go into search mode when it gets focus from the tab.

**Comment by chrissainty** [comment]
Thanks, but I really need an actual reproduction.  I can run any of the
samples in this repo, and tabing into the control and typing working
exactly as it should.

**Comment by vincentw56** [comment]
Okay, I've been able to reproduce this with your examples. Add this:

`<small class="form-text badge badge-danger"><ValidationMessage For="@(() => FormModel.SelectedPerson.Firstname)" /></small>`

You can see, it looks like if you have validation on the field, it has an issue. Otherwise, it works as expected.

**Comment by chrissainty** [comment]
Where abouts am I adding that code?

**Comment by vincentw56** [comment]
Any where you want to add it. It is simple validation. If you add validation to the field like the code I gave you, it doesn't work properly.
________________________________

**Comment by chrissainty** [comment]
This is the very first example in the sample app

```csharp
<EditForm Model="FormModel" OnValidSubmit="HandleFormSubmit">
    <DataAnnotationsValidator />

    <BlazoredTypeahead SearchMethod="GetPeopleLocal"
                       @bind-Value="FormModel.SelectedPerson"
                       EnableDropDown="true"
                       placeholder="Search by first name...">
        <SelectedTemplate Context="person">
            @person.Firstname
        </SelectedTemplate>
        <ResultTemplate Context="person">
            @person.Firstname @person.Lastname
        </ResultTemplate>
    </BlazoredTypeahead>
    <ValidationMessage For="@(() => FormModel.SelectedPerson)" />

    <button class="btn btn-primary" type="submit" style="margin-top: 20px;">Submit</button>
</EditForm>
```

It has validation and works fine.

**Comment by vincentw56** [comment]
Here is my test project that doesn't work. Everything I am doing is standard Bootstrap coding and styling.
[BlazorApp1.zip](https://github.com/Blazored/Typeahead/files/3929545/BlazorApp1.zip)

**Comment by rgamage** [comment]
Thanks Vincent for helping to repro this.  For what it's worth, I get this bad behavior without any Form at all, no validation code or elements.  However when I use ValueChanged instead of @bind-Value, everything works fine.  I'm using OnValueChanged in one project because I made a wrapper around the blazored-typeahead, and needed the ValueChanged event in order to propagate the notification up to the parent component (is there a better way?).  I still haven't been able to create a good pair of working/non-working examples, but I'll keep working on it.

**Comment by rgamage** [comment]
I think I pinned it down to these two cases, at least for me:

Working:
```
    [Parameter]
    public PartSearchViewModel SelectedPart { get; set; }
```

Not working:
```
    [Parameter]
    public PartSearchViewModel SelectedPart = new PartSearchViewModel();
```

In the non-working case, I am initializing the selected item in the declaration.  That, apparently, causes an issue where the input box is not working (cannot enter text, does not show placeholder), until you focus and type Enter key, or mouse click inside.  In my case there is no need for me to initialize the property, so I am just using the working case now.

**Comment by vincentw56** [comment]
Using the information provided by @rgamage, I think I found what is causing the issue. Using my uploaded project as is, shows it is broken. But, if you go into the FormExample.cs file and comment out this line:

`this.SelectedPerson = new Person();`

it works as expected. But it should work just fine with the line in there. And the current project I am working on needs me to instantiate the objects otherwise the form throws "Object not initialized errors".

**Comment by chrissainty** [comment]
Thanks for all the information @rgamage @vincentw56 I can see the issue now. The control checks if the `Value` is null or not to decide if it has a value. As this is not evaluating to `null` because of the initialisation, the control is trying to go into display mode rather than edit mode.

**Comment by chrissainty** [comment]
@vincentw56 Are your objects are overriding `Equals` or implementing `IEquatable<T>`?

**Comment by vincentw56** [comment]
> @vincentw56 Are your objects are overriding `Equals` or implementing `IEquatable<T>`?

No, it is just a standard initialization like the code above.

**Comment by chrissainty** [comment]
I don't think this is going to be an easy one to resolve, this is a bit out of my knowledge range so happy to take any advice here. But I don't think I can check complex objects for their default values without you implementing some code on your side. Would this be something you would be willing to do?

**Comment by rgamage** [comment]
My personal preference with this kind of situation is that the initial value of an object like "SelectedPerson" should be null, as that is an accurate representation of the current state - nothing has been selected.  Our app's code should handle that state gracefully, as it is expected. Setting it to a new Person() implies that the user has chosen an "empty" person with no name, etc. which doesn't seem right to me.  In any case, philosophical questions aside, may I suggest a possible solution?  I think it is reasonable to expect that some users may want the control to initialize to some default, or initial value, rather than null (empty), but this seems to cause a problem as currently implemented.  Rather than guessing what a custom object's default value is, why not add a parameter to the component, like InitialValue?  That way, the user could set it, and it could be dynamic, depending on the app state, etc.  Or it may make more sense to make it a method:

```
<BlazoredTypeahead Initializer="@(() => new Person())" ...  />
```
Or something similar?

**Comment by chrissainty** [comment]
I think for now I'm going to leave things as they are. I agree with your comments @rgamage:

> My personal preference with this kind of situation is that the initial value of an object like "SelectedPerson" should be null, as that is an accurate representation of the current state - nothing has been selected. Our app's code should handle that state gracefully, as it is expected. Setting it to a new Person() implies that the user has chosen an "empty" person with no name, etc. which doesn't seem right to me.

**Comment by vincentw56** [comment]
Technically it is not a philosophical question. There is a very real possibility of using initialized values. If I add two `<InputText>` controls that are bound to `FormModel.SelectedPerson.FirstName` and `FormModel.SelectedPerson.LastName`, the runtime compiler throws "Object not initialized" errors or something like that. This is because SelectedPerson is null so it cannot find the properties. Programmers use complex objects all the time and my form has several of them.

**Comment by vertonghenb** [comment]
To address the original question
> I am unable to use the typeahead control as a keyboard-centric user. I tab through the form's controls until the typeahead has focus, then try to start typing. Nothing happens. No apparent way to start entering text unt

If the control has a selected value or selected values (in multiselect), we chose to not be able to start typing directly when the control has focus since it could lead to a poor user experience:
Image you have an EditForm with multiple inputs in it (e.g. Text, Numbers, ... a Typeahead) and the order is as follows:
- Name (text)
- Country (typeahead)
- Age

As a user you **only** want to change the value of age so you start tabbing through the form. If you focus the typeahead the **country** would be changed when this is not what you'd expect since you were simply tabbing through to get to the age field. 

However if you want to change the country value, you can tab through the form and when you're in the typeahead you press enter to activate the search possibility. At this point the value of country can be changed as this is what the user would want.

**Comment by vertonghenb** [comment]
Back to the original question:
> With my testing so far (v 4.2.0), I am unable to use the typeahead control as a keyboard-centric user. I tab through the form's controls until the typeahead has focus, then try to start typing. Nothing happens. No apparent way to start entering text until I click with the mouse inside the input box.
> It would be great if, upon gaining focus, the typeahead control was able to receive keyboard input.

PR #106 should fix this:
![Example](https://i.imgur.com/aKvbBIp.gif)
