### ISSUE TITLE
Add a parameter for keep text entered when blur

### ISSUE THREAD

**Issue by julienGrd** [Blazored/Typeahead#97]
Hello chris, It would be good to have an option to keep the text enter valid even if the user click outside
actually, if i write some text and i click outside the result, my text disappear. I would like to keep the text and then when i focus again have the search relaunch with my text.

I can suggest a PR if needed.

thanks again !

Julien

**Comment by chrissainty** [comment]
Hi Julien,

We did have this behaviour but it was changed to clear the search text upon focus. The reason was that leaving old search text which might not match the current selection just looked odd and made search more tedious in certain scenarios. The user would have to clear text before being able to enter a new search phrase for example. 

This is a bit of a no-win scenario as some may like retaining the text, others may not. But, for the moment, I'm going to keep things as they are. 

Hope that makes sense.

**Comment by julienGrd** [comment]
Yeah i understand, i will fork your project to make this kind of modification, so if one day you want reintegrate this i will can make a PR
